Repository hash-define-organization/Hacktoberfest2020, pull requests merged in 2020-10, with the labels that each got.

#5 Updated Information
  CONTRIBUTORS.md
  README.md
  logo.png
  profiles/Utkarsh Sharma.md
  scripts/hello_world_utkarsh.cpp
Labels: Hashdefine-organization

#7 added to contributors.md
  CONTRIBUTORS.md
  README.md
  Sudoku Solver
  scripts/hello_world_jai.java
  scripts/printnodeskaway.java
Labels: Hashdefine-organization

#11 add aecuto profile
  profiles/aecuto.md
  scripts/aecut.js
Labels: Hacktoberfest2020, hacktoberfest-accepted

#18 Update CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#10 I'm following the tutorial
  CONTRIBUTORS.md
  hello_world_lucianotapia.php
  luciano_tapia.md
Labels: hacktoberfest-accepted

#19 fixed image
  README.md
Labels: hacktoberfest-accepted

#21 Hello World in JavaScript
  scripts/helloWorld.js
Labels: hacktoberfest-accepted

#15 Hritwika Sarkar
  CONTRIBUTORS.md
  profiles/Hritwika_Sarkar.md
  scripts/hello_world_Hrit20.java
Labels: hacktoberfest-accepted

#24 Add files via upload
  CALCULATOR.CPP
Labels: hacktoberfest-accepted

#22 Add files via upload
  DLL.CPP
Labels: hacktoberfest-accepted

#12 Add profile boscahya
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#25 Add files via upload
  ANIMATED.CPP
Labels: hacktoberfest-accepted

#28 added to scripts
  scripts/mergingarrays.java
  scripts/partition_in_array.java
  scripts/sorting.java
Labels: hacktoberfest-accepted
